In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.1.1-cp39-cp39-macosx_10_9_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 389.3 kB/s eta 0:00:0000:0100:01
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-1.26.0-cp39-cp39-macosx_10_9_x86_64.whl (20.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 321.9 kB/s eta 0:00:0000:0100:02
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/putmanti/Library/Caches/pypoetry/virtualenvs/linkml-project-template-AkzsagWH-py3.9/lib/python3.9/site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Collecting tzdata>=2022.1 (from pandas)
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: six>=1.5 in /Users/putmanti/Library/Caches/pypoetry/virtualenvs/linkml-project-template-AkzsagWH-py3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-1.26.0 pandas-2.1.1 pytz-2023.3.post1 tzdata-2023.3

[notice] A new release of pip is available: 23.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip

In [1]:
from include_linkml.include_pydantic import Biospecimen, Participant
from include_linkml.include_pydantic import EnumFamilyType, EnumSex
import pandas as pd
import dataclasses
from random import randint

ModuleNotFoundError: No module named 'pandas'

In [4]:
khor = pd.read_excel('data/Khor 2022-08-29 INCLUDE Down Syndrome Cohort Concurrent Conditions.xlsx',
                     sheet_name='Sheet1')

all_harmonized = pd.read_csv('data/all_cohorts_participant_2023-06-08.csv', sep=',')
bri_dsr = all_harmonized[all_harmonized['Study Code']=='BRI-DSR']

In [5]:
khor

,BRI INCLUDE ID,Patient Type,Age at Enrollment,Race,Gender,Ethnicity (hispanic/latino y/n),ADHD,Autisim,Dravet Syndrome or Lennox Gastaut,Ds Catatonia,Dysautonomia,Dystonia,Epilepsy,Epileptic Encephalopathy,Hirschsprung's Disease,Hypotonia,STRADA,Unverricht-Lundborg Disease
0,INCLUDE000907,Down Syndrome,53,"White, Caucasian",male,no,,,,,,,,,,,,
1,INCLUDE027754,Down Syndrome,27,"Asian, White, Caucasian",female,no,,,,,,,,,,,,
2,INCLUDE045500,Down Syndrome,3,"White, Caucasian",male,no,,,,,,,,,,,,
3,INCLUDE048781,Down Syndrome,9,"White, Caucasian",male,no,,,,,,,,,,,,
4,INCLUDE050246,Down Syndrome,10,"White, Caucasian",male,no,,,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,INCLUDE959871,Down Syndrome,10,Asian,female,no,,,,,,,,,,,,
163,INCLUDE959923,Down Syndrome,13,"White, Caucasian",male,no,,Autism,,,,,,,,,,
164,INCLUDE967357,Down Syndrome,7,"White, Caucasian",male,no,,,,,,,,,,,,
165,INCLUDE978703,Down Syndrome,2,"White, Caucasian",male,yes,,,,,,,,,,,,
166,INCLUDE998058,Down Syndrome,4,"Black, African American",female,no,,,,,,,,,,,,

In [3]:
khor.head()

,BRI INCLUDE ID,Patient Type,Age at Enrollment,Race,Gender,Ethnicity (hispanic/latino y/n),ADHD,Autisim,Dravet Syndrome or Lennox Gastaut,Ds Catatonia,Dysautonomia,Dystonia,Epilepsy,Epileptic Encephalopathy,Hirschsprung's Disease,Hypotonia,STRADA,Unverricht-Lundborg Disease
0,INCLUDE000907,Down Syndrome,53,"White, Caucasian",male,no,,,,,,,,,,,,
1,INCLUDE027754,Down Syndrome,27,"Asian, White, Caucasian",female,no,,,,,,,,,,,,
2,INCLUDE045500,Down Syndrome,3,"White, Caucasian",male,no,,,,,,,,,,,,
3,INCLUDE048781,Down Syndrome,9,"White, Caucasian",male,no,,,,,,,,,,,,
4,INCLUDE050246,Down Syndrome,10,"White, Caucasian",male,no,,,,,,,,,,,,

In [6]:
khor['Patient Type'].value_counts()

Patient Type
Down Syndrome    167
Name: count, dtype: int64

In [4]:

all_harmonized = pd.read_csv('data/all_cohorts_participant_2023-06-08.csv', sep=',')
bri_dsr = all_harmonized[all_harmonized['Study Code']=='BRI-DSR']

In [5]:

bri_dsr

,Study Code,Participant Global ID,Participant External ID,Family ID,Family Type,Father ID,Mother ID,Sibling ID,Other Family Member ID,Family Relationship,Sex,Race,Ethnicity,Down Syndrome Status,Age at First Patient Engagement,First Patient Engagement Event,Outcomes Vital Status,Age at Last Vital Status
417,BRI-DSR,pt-jcfhqfrhjw,INCLUDE000907,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,19358,Enrollment,NaN,NaN
418,BRI-DSR,pt-af7a4ra2xz,INCLUDE027754,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Female,More than one race,Not Hispanic or Latino,T21,9862,Enrollment,NaN,NaN
419,BRI-DSR,pt-mxzdd6qcyq,INCLUDE045500,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,1096,Enrollment,NaN,NaN
420,BRI-DSR,pt-ikf4qf4ycm,INCLUDE048781,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,3287,Enrollment,NaN,NaN
421,BRI-DSR,pt-fq3kmmb8wi,INCLUDE050246,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,3652,Enrollment,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
579,BRI-DSR,pt-8cizmydm8p,INCLUDE959871,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Female,Asian,Not Hispanic or Latino,T21,3652,Enrollment,NaN,NaN
580,BRI-DSR,pt-hj8be4jgzm,INCLUDE959923,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,4748,Enrollment,NaN,NaN
581,BRI-DSR,pt-yexpqf8w9m,INCLUDE967357,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Not Hispanic or Latino,T21,2557,Enrollment,NaN,NaN
582,BRI-DSR,pt-pr9xiwitiy,INCLUDE978703,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Male,White,Hispanic or Latino,T21,730,Enrollment,NaN,NaN
583,BRI-DSR,pt-j63mpfyb9f,INCLUDE998058,NaN,Proband-only,NaN,NaN,NaN,NaN,Proband,Female,Black or African American,Not Hispanic or Latino,T21,1461,Enrollment,NaN,NaN

In [7]:
bri_dsr['First Patient Engagement Event'].value_counts()

First Patient Engagement Event
Enrollment    167
Name: count, dtype: int64

In [6]:
Participant.__fields__

{'hasStudy': ModelField(name='hasStudy', type=Optional[Study], required=False, default=None),
 'participantGlobalId': ModelField(name='participantGlobalId', type=Optional[str], required=False, default=None),
 'participantExternalId': ModelField(name='participantExternalId', type=str, required=True),
 'familyId': ModelField(name='familyId', type=Optional[str], required=False, default=None),
 'familyType': ModelField(name='familyType', type=EnumFamilyType, required=True),
 'fatherId': ModelField(name='fatherId', type=Optional[str], required=False, default=None),
 'motherId': ModelField(name='motherId', type=Optional[str], required=False, default=None),
 'siblingId': ModelField(name='siblingId', type=Optional[str], required=False, default=None),
 'otherFamilyMemberId': ModelField(name='otherFamilyMemberId', type=Optional[str], required=False, default=None),
 'familyRelationship': ModelField(name='familyRelationship', type=Optional[EnumFamilyRelationship], required=False, default=None),
 'sex': ModelField(name='sex', type=EnumSex, required=True),
 'race': ModelField(name='race', type=EnumRace, required=True),
 'ethnicity': ModelField(name='ethnicity', type=EnumEthnicity, required=True),
 'downSyndromeStatus': ModelField(name='downSyndromeStatus', type=EnumDownSyndromeStatus, required=True),
 'ageAtFirstPatientEngagement': ModelField(name='ageAtFirstPatientEngagement', type=int, required=True),
 'firstPatientEngagementEvent': ModelField(name='firstPatientEngagementEvent', type=str, required=True),
 'outcomesVitalStatus': ModelField(name='outcomesVitalStatus', type=Optional[EnumVitalStatus], required=False, default=None),
 'ageAtLastVitalStatus': ModelField(name='ageAtLastVitalStatus', type=Optional[int], required=False, default=None)}

male

ValidationError: 6 validation errors for Participant
sex
  field required (type=value_error.missing)
race
  field required (type=value_error.missing)
ethnicity
  field required (type=value_error.missing)
downSyndromeStatus
  field required (type=value_error.missing)
ageAtFirstPatientEngagement
  field required (type=value_error.missing)
firstPatientEngagementEvent
  field required (type=value_error.missing)

In [18]:
EnumSex.male